<?php
declare(strict_types=1);
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service | SIP & SWP Calculator</title>
    <meta name="description"
        content="Terms of Service for the SIP & SWP Calculator. Please read these terms carefully before using our financial tools.">
    <link rel="canonical" href="https://sipswpcalculator.com/terms">

    <link rel="stylesheet" href="styles.css?v=<?= filemtime(__DIR__ . '/styles.css') ?>">
    <link rel="stylesheet" href="dist/tailwind.min.css?v=<?= filemtime(__DIR__ . '/dist/tailwind.min.css') ?>">
</head>

<body class="bg-gray-50 text-gray-800 font-sans antialiased"
    style="background-image: var(--gradient-surface); background-attachment: fixed;">
    <?php include 'navbar.php'; ?>

    <div class="max-w-4xl mx-auto p-4 sm:p-6 lg:p-8">
        <header class="mb-12 text-center">
            <h1 class="text-4xl font-extrabold pb-2">
                <span class="text-gradient">Terms of Service</span>
            </h1>
            <p class="text-lg text-gray-500 font-medium mt-2">Last Updated: February 2026</p>
        </header>

        <main class="glass-card p-8 sm:p-12">
            <article class="prose prose-lg max-w-none text-gray-600 prose-headings:text-indigo-900">
                <h2>1. Acceptance of Terms</h2>
                <p>By accessing and using sipswpcalculator.com ("the Website"), you accept and agree to be bound by the
                    terms and provision of this agreement.</p>

                <h2>2. Educational Purposes Only (Disclaimer)</h2>
                <p>The calculators and content provided on this Website are for <strong>educational and illustrative
                        purposes only</strong>. The estimates and projections do not account for hidden fees, sudden tax
                    rule changes, or extreme market volatility.</p>
                <p>We are not registered financial advisors, and the information presented does not constitute
                    professional financial, tax, or investment advice. Always consult a certified financial planner
                    before making investment decisions.</p>

                <h2>3. Accuracy of Information</h2>
                <p>While we strive to keep our formulas and tax rate information up to date (including 2026
                    adjustments), we make no warranties regarding the absolute accuracy, completeness, or reliability of
                    the results generated by the tools.</p>

                <h2>4. Intellectual Property</h2>
                <p>The design, code, and original content of this Website are protected by copyright. You may use the
                    generated PDF reports and CSV exports for personal use, but you may not scrape, clone, or
                    redistribute the underlying calculator logic without permission.</p>

                <h2>5. Limitation of Liability</h2>
                <p>In no event shall sipswpcalculator.com or its creators be liable for any direct, indirect,
                    incidental, consequential, or punitive damages arising out of your use of, or inability to use, the
                    Website and its calculators.</p>

                <div class="mt-8 pt-6 border-t border-gray-200 text-center">
                    <a href="/" class="text-indigo-600 hover:underline font-medium">← Return to SIP & SWP Calculator</a>
                </div>
            </article>
        </main>

        <?php include 'footer.php'; ?>
    </div>
</body>

</html>