<?php
declare(strict_types=1);
require_once __DIR__ . '/functions.php';

$page_config = [
    'title' => 'Terms of Service | SIP & SWP Calculator',
    'meta_desc' => 'Terms of Service for the SIP & SWP Calculator. Please read these terms carefully before using our financial tools.',
    'canonical' => 'https://sipswpcalculator.com/terms',
];

ob_start();
?>
<meta name="robots" content="noindex, follow">
<?php
$page_config['additional_head'] = ob_get_clean();
$active_page = 'terms.php';

ob_start();
?>

<header class="relative mb-6 sm:mb-10 text-center">
    <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-slate-100 border border-slate-200 mb-4">
        <span class="text-sm font-semibold text-slate-600 tracking-wide uppercase">Legal Document</span>
    </div>

    <h1 class="text-3xl sm:text-5xl md:text-7xl font-extrabold pb-3 tracking-tight">
        <span class="text-gradient">Terms of Service</span>
    </h1>

    <p class="text-base sm:text-lg text-gray-500 max-w-2xl mx-auto leading-relaxed font-medium mb-4">
        Last Updated: March 2026
    </p>
</header>

<main class="glass-card p-8 sm:p-12 max-w-4xl mx-auto">
    <article
        class="prose prose-lg max-w-none text-gray-600 prose-headings:text-indigo-900 prose-a:text-indigo-600 hover:prose-a:text-indigo-500 prose-strong:text-gray-800">
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using sipswpcalculator.com ("the Website"), you accept and agree to be bound by the
            terms and provision of this agreement.</p>

        <h2>2. Educational Purposes Only (Disclaimer)</h2>
        <p>The calculators and content provided on this Website are for <strong>educational and illustrative
                purposes only</strong>. The estimates and projections do not account for hidden fees, sudden tax
            rule changes, or extreme market volatility.</p>
        <p>We are not registered financial advisors, and the information presented does not constitute
            professional financial, tax, or investment advice. Always consult a certified financial planner
            before making investment decisions.</p>

        <h2>3. Accuracy of Information</h2>
        <p>While we strive to keep our formulas and tax rate information up to date (including 2026
            adjustments), we make no warranties regarding the absolute accuracy, completeness, or reliability of
            the results generated by the tools.</p>

        <h2>4. Intellectual Property</h2>
        <p>The design, code, and original content of this Website are protected by copyright. You may use the
            generated PDF reports and CSV exports for personal use, but you may not scrape, clone, or
            redistribute the underlying calculator logic without permission.</p>

        <h2>5. Limitation of Liability</h2>
        <p>In no event shall sipswpcalculator.com or its creators be liable for any direct, indirect,
            incidental, consequential, or punitive damages arising out of your use of, or inability to use, the
            Website and its calculators.</p>

    </article>
</main>
<div class="mt-8 pt-6 border-t border-gray-200 text-center">
    <a href="/#calculator-section" class="text-indigo-600 hover:underline font-medium">← Return to Calculator</a>
</div>

<?php
$page_content = ob_get_clean();
require_once __DIR__ . '/includes/layout.php';
?>